DELETE http://localhost:8080/remove-wallet-user/wallet/2/username/test_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA3MzM1MzIsInVzZXJfaWQiOjJ9.IwQkmuabj1OOFX6tQBmRsPnD2khRWXwCEhjOr3p3KmQ