POST http://localhost:8080/share-wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTA0NzE1MTAsInVzZXJfaWQiOjJ9.yeFxvKMY5DagD8EVDAAmymid-KKyVCj-bAUdBStmzkk

{
    "wallet_id": 2,
    "username": "test_user",
    "user_role": "user"
}