POST http://localhost:8080/add-income
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEwODAwMzIsInVzZXJfaWQiOjJ9.bQVdfjQCisRnfMGdpLLXkFLHyOIUARogT8olhV_Cn74

{
    "amount": 100000,
    "category": "Salary",
    "wallet_id": 1
}