POST http://localhost:8080/add-expense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEwODAwMzIsInVzZXJfaWQiOjJ9.bQVdfjQCisRnfMGdpLLXkFLHyOIUARogT8olhV_Cn74
Content-Type: application/json

{
    "amount": 200000,
    "category": "Clothes",
    "wallet_id": 1
}