POST http://localhost:8080/add-expense
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTEwMDA5MDEsInVzZXJfaWQiOjJ9.0Nm1EwJxvW-7IEYgGDMVCISMklExrVObe8csVIakoRA
Content-Type: application/json

{
    "amount": 2000,
    "category": "Clothes",
    "wallet_id": 1
}