POST http://localhost:8080/new-wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE1MTU3MzQsInVzZXJfaWQiOjF9.pA9x1A0W7tNxeLbY7e1tq-bHx0rWennoicwFd0uXkts
Content-Type: application/json

{
    "wallet_name": "test_wallet",
    "currency": "RUB"
}