POST http://localhost:8080/share-wallet
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTIyOTM5ODUsInVzZXJfaWQiOjF9.6fx5fFrchp2sLCfqkBNbhOuSc6GnJ-VleIZB8P-ShrM
Content-Type: application/json

{
    "wallet_id": 1,
    "username": "test_user_2",
    "user_role": "admin"
}